### ISSUE TITLE
yaml exception with example code in README

### ISSUE THREAD

**Issue by paolini** [serverless/serverless-client-s3#54]
In REAMDE.md you suggest to add these line to serverless.yml:

```
plugins:
  - serverless-client-s3
 custom:
   client:
     bucketName: serverless-client-bucketname

```
however this seems not to be valid yml. When executing `serverless client deploy` I get the following YAML exception:

```
  bad indentation of a mapping entry in "/Users/paolini/notes/serverless.yml" at line 59, column 2:
     custom:
     ^

```
